# Generated by Django 6.0.1 on 2026-02-25 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='core.category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='excerpt',
            field=models.TextField(verbose_name='Resumen/Bajada'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL Imagen Destacada'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
